INSERT INTO distributor (
    id,
    organization_id,
    customer_id,
    customer_site_id,
    document,
    status,
    max_sale_voucher,
    validate_price_method_code,
    send_complete_voucher,
    headquarter_id,
    is_send_sms,
    main_customer_address,
    micro_market,
    monthly_max_voucher_sales_allowed,
    sms_sell_template_message,
    sms_cancel_template_message,
    validity_start_date,
    allow_voucher_transfer,
    name,
    state_abbreviation,
    city,
    daily_voucher_sell_limit,
    contact_email,
    partnership_type,
    reconciliation_code,
    validation_method_on_voucher_block,
    cpf_phone_number_required,
    billing_date
) VALUES (
    90000001,
    5,
    100000,
    200000,
    '03282579000110',
    'A',
    99,
    'BY_CNPJ',
    0,
    NULL,
    0,
    1,
    'MM',
    9999,
    'Venda autorizada',
    'Venda cancelada',
    '2026-01-01',
    1,
    'Distribuidor Local Playwright',
    'BA',
    'Salvador',
    9999,
    'local-playwright@example.com',
    NULL,
    'E2E',
    NULL,
    0,
    1
) ON DUPLICATE KEY UPDATE
    organization_id = VALUES(organization_id),
    customer_id = VALUES(customer_id),
    customer_site_id = VALUES(customer_site_id),
    document = VALUES(document),
    status = VALUES(status),
    max_sale_voucher = VALUES(max_sale_voucher),
    validate_price_method_code = VALUES(validate_price_method_code),
    send_complete_voucher = VALUES(send_complete_voucher),
    headquarter_id = VALUES(headquarter_id),
    is_send_sms = VALUES(is_send_sms),
    main_customer_address = VALUES(main_customer_address),
    micro_market = VALUES(micro_market),
    monthly_max_voucher_sales_allowed = VALUES(monthly_max_voucher_sales_allowed),
    sms_sell_template_message = VALUES(sms_sell_template_message),
    sms_cancel_template_message = VALUES(sms_cancel_template_message),
    validity_start_date = VALUES(validity_start_date),
    allow_voucher_transfer = VALUES(allow_voucher_transfer),
    name = VALUES(name),
    state_abbreviation = VALUES(state_abbreviation),
    city = VALUES(city),
    daily_voucher_sell_limit = VALUES(daily_voucher_sell_limit),
    contact_email = VALUES(contact_email),
    partnership_type = VALUES(partnership_type),
    reconciliation_code = VALUES(reconciliation_code),
    validation_method_on_voucher_block = VALUES(validation_method_on_voucher_block),
    cpf_phone_number_required = VALUES(cpf_phone_number_required),
    billing_date = VALUES(billing_date);

INSERT INTO product (
    id,
    code,
    name,
    description
) VALUES (
    '90000001-0000-4000-8000-000000000001',
    '0110035',
    'P13',
    'Carga GLP P13'
) ON DUPLICATE KEY UPDATE
    code = VALUES(code),
    name = VALUES(name),
    description = VALUES(description);

INSERT INTO rel_distributor_product (
    id,
    distributor_id,
    product_id,
    product_price,
    valid_date_begin,
    valid_date_end,
    discount,
    commission_amount,
    payment_terms
) VALUES (
    90000001,
    90000001,
    '90000001-0000-4000-8000-000000000001',
    120.00,
    '2026-01-01 00:00:00',
    NULL,
    0.00,
    0.00,
    0
) ON DUPLICATE KEY UPDATE
    distributor_id = VALUES(distributor_id),
    product_id = VALUES(product_id),
    product_price = VALUES(product_price),
    valid_date_begin = VALUES(valid_date_begin),
    valid_date_end = VALUES(valid_date_end),
    discount = VALUES(discount),
    commission_amount = VALUES(commission_amount),
    payment_terms = VALUES(payment_terms);
